name: run-script
on:
  workflow_dispatch:
    branches: master
permissions:
  contents: write
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      # Checkout this repo
      - uses: actions/checkout@v4

      # Install R
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Install R packages
      - uses: r-lib/actions/setup-r-dependencies@v2

      # Run script
      - name: Fetch latest data
      run: Rscript news_api.R
