on:
  push:
    branches: master

name: script

jobs:
  script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
    steps:
      # Checkout repos
      - uses: actions/checkout@v4

      # Install R
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Install R packages
      - uses: r-lib/actions/setup-r-dependencies@v2

      # Run script
      - name: Fetch latest data
      run: Rscript news_api.R

